# 도커 X
name: CI/CD Pipeline (.jar)

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: develop 체크아웃
        uses: actions/checkout@v4 # 체크아웃

      - name: 자바 설정 # Java 개발 킷 설정
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: application.yml 대체
        run: |
          cd ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./application.yml
        shell: bash

      - name: gradlew 실행 권한 부여
        run: chmod +x gradlew

      - name: gradle 세팅
        uses: gradle/actions/setup-gradle@v4

      - name: gradle 빌드
        run: ./gradlew build

      - name: 빌드된 아티팩트 업로드
        uses: actions/upload-artifact@v4
        with:
          name: BackEnd
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 아티팩트 다운로드
        uses: actions/download-artifact@v4
        with:
          name: BackEnd
          path: build/libs/

      - name: EC2 배포
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          jar_file=$(find build/libs -name '*.jar' ! -name '*plain.jar' | head -n 1)
          scp -i private_key.pem -o StrictHostKeyChecking=no "$jar_file" $EC2_USERNAME@$EC2_HOST:/home/$EC2_USERNAME/BackEnd.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_HOST "
            pgrep java | xargs -r kill -15  # 기존에 실행 중인 Java 프로세스 종료
            sleep 10
            nohup java -jar /home/$EC2_USERNAME/BackEnd.jar > app.log 2>&1 &  # 새 버전 애플리케이션 실행
          "
          rm -f private_key.pem  # 민감한 정보 삭제
